/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#10b981",
        "tertiary": "#e11d48",
        "primary-container": "#dbeafe",
        "on-error-container": "#7f1d1d",
        "on-background": "#0f172a",
        "error": "#dc2626",
        "on-secondary-container": "#064e3b",
        "on-primary": "#ffffff",
        "outline-variant": "#e2e8f0",
        "surface-container": "#f1f5f9",
        "primary-dim": "#1d4ed8",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#2563eb",
        "surface-dim": "#f8fafc",
        "outline": "#94a3b8",
        "on-surface-variant": "#64748b",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#1e3a8a",
        "background": "#ffffff",
        "secondary": "#059669",
        "tertiary-fixed-dim": "#be123c",
        "error-container": "#fee2e2",
        "surface-container-highest": "#cbd5e1",
        "inverse-surface": "#1e293b",
        "on-secondary-fixed-variant": "#064e3b",
        "on-tertiary-fixed": "#4c0519",
        "inverse-primary": "#93c5fd",
        "surface-container-low": "#f8fafc",
        "tertiary-fixed": "#fb7185",
        "secondary-container": "#d1fae5",
        "secondary-dim": "#059669",
        "surface-bright": "#ffffff",
        "on-primary-fixed": "#1e3a8a",
        "on-surface": "#0f172a",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#3b82f6",
        "on-primary-fixed-variant": "#1d4ed8",
        "surface": "#ffffff",
        "inverse-on-surface": "#f1f5f9",
        "on-tertiary-fixed-variant": "#9f1239",
        "primary": "#2563eb",
        "on-tertiary-container": "#4c0519",
        "surface-variant": "#f8fafc",
        "secondary-fixed-dim": "#10b981",
        "tertiary-container": "#ffe4e6",
        "error-dim": "#b91c1c",
        "primary-fixed": "#2563eb",
        "tertiary-dim": "#e11d48",
        "on-secondary": "#ffffff",
        "surface-container-high": "#f1f5f9",
        "on-secondary-fixed": "#064e3b"

      },
      fontFamily: {
        "headline": ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "body": ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "label": ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"]
      },
      borderRadius: {
        "sm": "4px",
        "md": "6px",
        "lg": "8px",
        "xl": "10px",
        "2xl": "14px",
        "3xl": "20px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
